### PR TITLE
Update to Ruby 2.3.0, finish README, add to Travis

### PR DESCRIPTION
**Pull request by mathias**

### CODE REVIEW

**Comment by cdwort** [comment]
Besides lack of .travis.yml (or other unknown solution to Travis running the wrong Ruby), it looks good to me.

**Comment by mathias** [comment]
There, that should do it for the `.travis.yml` file

**Comment by cdwort** [comment]
Woot!

**Comment by mathias** [comment]
This probably needs to be bumped to Ruby 2.3.0 now ;)

**Comment by mattreduce** [comment]
\(^_^)/ +1 on bumping to 2.3.0, this currently looks good to me, though

**Comment by mathias** [comment]
Anything else needed in the README? @cdwort @mattreduce

**Comment by cdwort** [comment]
Given how comprehensive the DevCenter article is, I don't see anything else to add.

LGTM from my perspective.

**Comment by mattreduce** [comment]
@mathias @cdwort +1 I don't see anything missing currently :+1:

**Pull request merged**
